project_id = "muzik-pwa"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 100

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = false

[inbucket]
enabled = false

[storage]
enabled = false

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173/auth/callback", "http://127.0.0.1:5173/auth/callback"]
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = false
enable_confirmations = true

[functions.muzik]
verify_jwt = true

[analytics]
enabled = false
